"""
This is an instantiated file from 'graph_template' and it'll create a graph
of all relations of the 'vim' tag in the Note's app.
"""
import graphviz
import snoop
import streamlit as st
from snoop import pp


def type_watch(source, value):
    return f"type({source})", type(value)


@snoop
def template():
    """
    We'll map each tuple item as one node, and produce an undirected graph.
    """
    gr = graphviz.Graph(format="png")
    gr.edge("php code sniffer", "php")
    gr.edge("php code sniffer", "linter")
    gr.edge("php", "linter")
    gr.edge("vim", "ale")
    gr.edge("vim", "linter")
    gr.edge("ale", "linter")
    gr.edge("reusable_files", "insert")
    gr.edge("reusable_files", "command")
    gr.edge("insert", "command")
    gr.edge("date", "append")
    gr.edge("date", "file")
    gr.edge("append", "file")
    gr.edge("python", "lists")
    gr.edge("python", "file")
    gr.edge("lists", "file")
    gr.edge("python", "delete")
    gr.edge("python", "file")
    gr.edge("delete", "file")
    gr.edge("python", "files")
    gr.edge("python", "print")
    gr.edge("files", "print")
    gr.edge("mysql", "csv")
    gr.edge("mysql", "import")
    gr.edge("csv", "import")
    gr.edge("requirements.txt", "python")
    gr.edge("requirements.txt", "flask")
    gr.edge("python", "flask")
    gr.edge("zst", "zstd")
    gr.edge("zst", "compression")
    gr.edge("zstd", "compression")
    gr.edge("scss", "css")
    gr.edge("scss", "sass")
    gr.edge("css", "sass")
    gr.edge("lines", "files")
    gr.edge("lines", "python")
    gr.edge("files", "python")
    gr.edge("python", "directory")
    gr.edge("python", "file")
    gr.edge("directory", "file")
    gr.edge("files", "sed")
    gr.edge("files", "bash")
    gr.edge("sed", "bash")
    gr.edge("bash", "files")
    gr.edge("bash", "shell")
    gr.edge("files", "shell")
    gr.edge("gitignore", "git")
    gr.edge("gitignore", "ignore")
    gr.edge("git", "ignore")
    gr.edge("variables", "files")
    gr.edge("variables", "python")
    gr.edge("files", "python")
    gr.edge("files", "python")
    gr.edge("files", "current file")
    gr.edge("python", "current file")
    gr.edge("python", "paths")
    gr.edge("python", "file")
    gr.edge("paths", "file")
    gr.edge("isfile", "python")
    gr.edge("isfile", "file")
    gr.edge("python", "file")
    gr.edge("files", "bash")
    gr.edge("files", "script")
    gr.edge("bash", "script")
    gr.edge("python", "files")
    gr.edge("python", "edit")
    gr.edge("files", "edit")
    gr.edge("files", "line numbers")
    gr.edge("files", "python")
    gr.edge("line numbers", "python")
    gr.edge("sed", "awk")
    gr.edge("sed", "file")
    gr.edge("awk", "file")
    gr.edge("python", "import")
    gr.edge("python", "variables")
    gr.edge("import", "variables")
    gr.edge("importing", "mysql")
    gr.edge("importing", "import")
    gr.edge("mysql", "import")
    gr.edge("django", "sql")
    gr.edge("django", "mysql")
    gr.edge("sql", "mysql")
    gr.edge("vim", "current file")
    gr.edge("vim", "files")
    gr.edge("current file", "files")
    gr.edge("python", "current file")
    gr.edge("python", "path")
    gr.edge("current file", "path")
    gr.edge("javascript", "js")
    gr.edge("javascript", "terminal")
    gr.edge("js", "terminal")
    gr.edge("python", "import")
    gr.edge("python", "folders")
    gr.edge("import", "folders")
    gr.edge("sed", "short")
    gr.edge("sed", "file")
    gr.edge("short", "file")
    gr.edge("bash", "name")
    gr.edge("bash", "shell")
    gr.edge("name", "shell")
    gr.edge("awk", "sed")
    gr.edge("awk", "columns")
    gr.edge("sed", "columns")
    gr.edge("files", "insert")
    gr.edge("files", "line")
    gr.edge("insert", "line")
    gr.edge("terminal", "dimensions")
    gr.edge("terminal", "os")
    gr.edge("dimensions", "os")
    gr.edge("Vim", "folders")
    gr.edge("Vim", "file explorer")
    gr.edge("folders", "file explorer")
    gr.edge("GPG", "files")
    gr.edge("GPG", "encrypted")
    gr.edge("files", "encrypted")
    gr.edge("pickle", "lists")
    gr.edge("pickle", "entries")
    gr.edge("lists", "entries")
    gr.edge("mimetype", "file")
    gr.edge("mimetype", "type")
    gr.edge("file", "type")
    gr.edge("vim", "auto format")
    gr.edge("vim", "formatting")
    gr.edge("auto format", "formatting")
    gr.edge("vim", "formatting")
    gr.edge("vim", "html")
    gr.edge("formatting", "html")
    gr.edge("vim", "json")
    gr.edge("vim", "format")
    gr.edge("json", "format")
    gr.edge("vim", "argument")
    gr.edge("vim", "files")
    gr.edge("argument", "files")
    gr.edge("python", "package")
    gr.edge("python", "setup.py")
    gr.edge("package", "setup.py")
    gr.edge("arch", "source")
    gr.edge("arch", "aur")
    gr.edge("source", "aur")
    gr.edge("vim", "install")
    gr.edge("vim", "clipboard")
    gr.edge("install", "clipboard")
    gr.edge("patch", "dwm")
    gr.edge("patch", "wm")
    gr.edge("dwm", "wm")
    gr.edge("setup.cfg", "pip")
    gr.edge("setup.cfg", "python")
    gr.edge("pip", "python")
    gr.edge("pip", "extras")
    gr.edge("pip", "install")
    gr.edge("extras", "install")
    gr.edge("vim", "clipboard")
    gr.edge("vim", "ssh")
    gr.edge("clipboard", "ssh")
    gr.edge("vim", "install")
    gr.edge("vim", "clipboard")
    gr.edge("install", "clipboard")
    gr.edge("vim", "configuration")
    gr.edge("vim", "clipboard")
    gr.edge("configuration", "clipboard")
    gr.edge("vim", "ale")
    gr.edge("vim", "linter")
    gr.edge("ale", "linter")
    gr.edge("date", "unix")
    gr.edge("date", "time")
    gr.edge("unix", "time")
    gr.edge("line break", "unix")
    gr.edge("line break", "vim")
    gr.edge("unix", "vim")
    gr.edge("date", "Unix")
    gr.edge("date", "epoch")
    gr.edge("Unix", "epoch")
    gr.edge("Vim", "comment")
    gr.edge("Vim", "uncomment")
    gr.edge("comment", "uncomment")
    gr.edge("range", "increment")
    gr.edge("range", "length")
    gr.edge("increment", "length")
    gr.edge("vim", "columns")
    gr.edge("vim", "len")
    gr.edge("columns", "len")
    gr.edge("vim", "limit")
    gr.edge("vim", "length")
    gr.edge("limit", "length")
    gr.edge("vim", "auto format")
    gr.edge("vim", "formatting")
    gr.edge("auto format", "formatting")
    gr.edge("vim", "formatting")
    gr.edge("vim", "html")
    gr.edge("formatting", "html")
    gr.edge("quotation marks", "apostrophes")
    gr.edge("quotation marks", "quotations")
    gr.edge("apostrophes", "quotations")
    gr.edge("vim", "quotes")
    gr.edge("vim", "apostrophes")
    gr.edge("quotes", "apostrophes")
    gr.edge("xdg-open", "default")
    gr.edge("xdg-open", "xdg")
    gr.edge("default", "xdg")
    gr.edge("zst", "zstd")
    gr.edge("zst", "compression")
    gr.edge("zstd", "compression")
    gr.edge("port", "open port")
    gr.edge("port", "open")
    gr.edge("open port", "open")
    gr.edge("vim", "open")
    gr.edge("vim", "files")
    gr.edge("open", "files")
    gr.edge("kitty", "urls")
    gr.edge("kitty", "links")
    gr.edge("urls", "links")
    gr.edge("vim", "json")
    gr.edge("vim", "format")
    gr.edge("json", "format")
    gr.edge("json", "delete")
    gr.edge("json", "python")
    gr.edge("delete", "python")
    gr.edge("loads", "dumps")
    gr.edge("loads", "json")
    gr.edge("dumps", "json")
    gr.edge("terminal", "python")
    gr.edge("terminal", "json")
    gr.edge("python", "json")
    gr.edge("data", "error")
    gr.edge("data", "json")
    gr.edge("error", "json")
    gr.edge("vim", "limit")
    gr.edge("vim", "length")
    gr.edge("limit", "length")
    gr.edge("vim", "configuration")
    gr.edge("vim", "clipboard")
    gr.edge("configuration", "clipboard")
    gr.edge("Powerline", "configuration")
    gr.edge("Powerline", "python")
    gr.edge("configuration", "python")
    gr.edge("fulltext", "mysql")
    gr.edge("fulltext", "index")
    gr.edge("mysql", "index")
    gr.edge("users", "group")
    gr.edge("users", "ps")
    gr.edge("group", "ps")
    gr.edge("vim", "find")
    gr.edge("vim", "replace")
    gr.edge("find", "replace")
    gr.edge("sed", "lines")
    gr.edge("sed", "replace")
    gr.edge("lines", "replace")
    gr.edge("strings", "substring")
    gr.edge("strings", "python")
    gr.edge("substring", "python")
    gr.edge("tuples", "index")
    gr.edge("tuples", "indexes")
    gr.edge("index", "indexes")
    gr.edge("indexes", "strings")
    gr.edge("indexes", "python")
    gr.edge("strings", "python")
    gr.edge("strings", "sed")
    gr.edge("strings", "python")
    gr.edge("sed", "python")
    gr.edge("find", "empty")
    gr.edge("find", "files")
    gr.edge("empty", "files")
    gr.edge("vim", "commentary")
    gr.edge("vim", "comment")
    gr.edge("commentary", "comment")
    gr.edge("vim", "comment")
    gr.edge("vim", "plugin")
    gr.edge("comment", "plugin")
    gr.edge("bash", "comment")
    gr.edge("bash", "shell")
    gr.edge("comment", "shell")
    gr.edge("Vim", "comment")
    gr.edge("Vim", "uncomment")
    gr.edge("comment", "uncomment")
    gr.edge("web server", "server")
    gr.edge("web server", "php")
    gr.edge("server", "php")
    gr.edge("php code sniffer", "php")
    gr.edge("php code sniffer", "linter")
    gr.edge("php", "linter")
    gr.edge("php", "keybind")
    gr.edge("php", "vim")
    gr.edge("keybind", "vim")
    gr.edge("php", "refresh")
    gr.edge("php", "form")
    gr.edge("refresh", "form")
    gr.edge("php", "get")
    gr.edge("php", "post")
    gr.edge("get", "post")
    gr.edge("get", "urls")
    gr.edge("get", "php")
    gr.edge("urls", "php")
    gr.edge("php", "variables")
    gr.edge("php", "static")
    gr.edge("variables", "static")
    gr.edge("html", "refresh")
    gr.edge("html", "php")
    gr.edge("refresh", "php")
    gr.edge("backblaze", "duplicity")
    gr.edge("backblaze", "backup")
    gr.edge("duplicity", "backup")
    gr.edge("editor", "command line")
    gr.edge("editor", "editing")
    gr.edge("command line", "editing")
    gr.edge("calculator", "command line")
    gr.edge("calculator", "linux")
    gr.edge("command line", "linux")
    gr.edge("python", "directory")
    gr.edge("python", "file")
    gr.edge("directory", "file")
    gr.edge("marker", "commands")
    gr.edge("marker", "command")
    gr.edge("commands", "command")
    gr.edge("reusable_files", "insert")
    gr.edge("reusable_files", "command")
    gr.edge("insert", "command")
    gr.edge("Pickle", "Pickletools")
    gr.edge("Pickle", "command line")
    gr.edge("Pickletools", "command line")
    gr.edge("time", "commands")
    gr.edge("time", "processes")
    gr.edge("commands", "processes")
    gr.edge("timestamp", "time")
    gr.edge("timestamp", "add")
    gr.edge("time", "add")
    gr.edge("setup.cfg", "pip")
    gr.edge("setup.cfg", "python")
    gr.edge("pip", "python")
    gr.edge("notes", "command line")
    gr.edge("notes", "cli")
    gr.edge("command line", "cli")
    gr.edge("sphinx", "documentation")
    gr.edge("sphinx", "python")
    gr.edge("documentation", "python")
    gr.edge("vim", "spellcheck")
    gr.edge("vim", "spelling")
    gr.edge("spellcheck", "spelling")
    gr.edge("partials", "CONFIGS")
    gr.edge("partials", "partials")
    gr.edge("CONFIGS", "partials")
    gr.edge("bash", "comment")
    gr.edge("bash", "shell")
    gr.edge("comment", "shell")
    gr.edge("vim", "multiline")
    gr.edge("vim", "repeat")
    gr.edge("multiline", "repeat")
    gr.edge("copy", "paste")
    gr.edge("copy", "nano")
    gr.edge("paste", "nano")
    gr.edge("vim", "paste")
    gr.edge("vim", "copy")
    gr.edge("paste", "copy")
    gr.edge("remove", "strings")
    gr.edge("remove", "characters")
    gr.edge("strings", "characters")
    gr.edge("strings", "strings")
    gr.edge("strings", "python")
    gr.edge("strings", "python")
    gr.edge("strings", "replace")
    gr.edge("strings", "strings")
    gr.edge("replace", "strings")
    gr.edge("strings", "replace")
    gr.edge("strings", "remove")
    gr.edge("replace", "remove")
    gr.edge("list of lists", "lists")
    gr.edge("list of lists", "strings")
    gr.edge("lists", "strings")
    gr.edge("vim", "repeats")
    gr.edge("vim", "string")
    gr.edge("repeats", "string")
    gr.edge("shell", "variables")
    gr.edge("shell", "string")
    gr.edge("variables", "string")
    gr.edge("python", "characters")
    gr.edge("python", "string")
    gr.edge("characters", "string")
    gr.edge("sed", "substring")
    gr.edge("sed", "string")
    gr.edge("substring", "string")
    gr.edge("tuples", "strings")
    gr.edge("tuples", "convert")
    gr.edge("strings", "convert")
    gr.edge("sed", "strings")
    gr.edge("sed", "lines")
    gr.edge("strings", "lines")
    gr.edge("bytes", "strings")
    gr.edge("bytes", "converter")
    gr.edge("strings", "converter")
    gr.edge("strings", "belongs")
    gr.edge("strings", "string")
    gr.edge("belongs", "string")
    gr.edge("alphabet", "python")
    gr.edge("alphabet", "string")
    gr.edge("python", "string")
    gr.edge("indexes", "strings")
    gr.edge("indexes", "python")
    gr.edge("strings", "python")
    gr.edge("strings", "sed")
    gr.edge("strings", "python")
    gr.edge("sed", "python")
    gr.edge("tuples", "lists")
    gr.edge("tuples", "python")
    gr.edge("lists", "python")
    gr.edge("vim", "multiline")
    gr.edge("vim", "repeat")
    gr.edge("multiline", "repeat")
    gr.edge("lists", "strings")
    gr.edge("lists", "convert")
    gr.edge("strings", "convert")
    gr.edge("replace", "characters")
    gr.edge("replace", "string")
    gr.edge("characters", "string")
    gr.edge("width", "curses")
    gr.edge("width", "tput")
    gr.edge("curses", "tput")
    gr.edge("strings", "count")
    gr.edge("strings", "characters")
    gr.edge("count", "characters")
    gr.edge("characters", "strings")
    gr.edge("characters", "repeat")
    gr.edge("strings", "repeat")
    gr.edge("append", "joining")
    gr.edge("append", "list")
    gr.edge("joining", "list")
    gr.edge("vim", "auto format")
    gr.edge("vim", "formatting")
    gr.edge("auto format", "formatting")
    gr.edge("vim", "formatting")
    gr.edge("vim", "html")
    gr.edge("formatting", "html")
    gr.edge("vim", "json")
    gr.edge("vim", "format")
    gr.edge("json", "format")
    gr.edge("fabric", "remote")
    gr.edge("fabric", "ssh")
    gr.edge("remote", "ssh")
    gr.edge("vim", "clipboard")
    gr.edge("vim", "ssh")
    gr.edge("clipboard", "ssh")
    gr.edge("ssh", "cron")
    gr.edge("ssh", "server")
    gr.edge("cron", "server")
    gr.edge("ufw", "port")
    gr.edge("ufw", "range")
    gr.edge("port", "range")
    gr.edge("html", "icons")
    gr.edge("html", "links")
    gr.edge("icons", "links")
    gr.edge("files", "sed")
    gr.edge("files", "bash")
    gr.edge("sed", "bash")
    gr.edge("sed", "strings")
    gr.edge("sed", "lines")
    gr.edge("strings", "lines")
    gr.edge("django", "sql")
    gr.edge("django", "mysql")
    gr.edge("sql", "mysql")
    gr.edge("files", "insert")
    gr.edge("files", "line")
    gr.edge("insert", "line")
    gr.edge("tables", "INSERT")
    gr.edge("tables", "mysql")
    gr.edge("INSERT", "mysql")
    gr.edge("reusable_files", "insert")
    gr.edge("reusable_files", "command")
    gr.edge("insert", "command")
    gr.edge("black", "vim")
    gr.edge("black", "formatter")
    gr.edge("vim", "formatter")
    gr.edge("Vim", "eol")
    gr.edge("Vim", "od")
    gr.edge("eol", "od")
    gr.edge("vim", "commentary")
    gr.edge("vim", "comment")
    gr.edge("commentary", "comment")
    gr.edge("spelling", "vim")
    gr.edge("spelling", "spell")
    gr.edge("vim", "spell")
    gr.edge("vim", "spellcheck")
    gr.edge("vim", "spelling")
    gr.edge("spellcheck", "spelling")
    gr.edge("partials", "CONFIGS")
    gr.edge("partials", "partials")
    gr.edge("CONFIGS", "partials")
    gr.edge("aspell", "micro")
    gr.edge("aspell", "plugin")
    gr.edge("micro", "plugin")
    gr.edge("vim", "comment")
    gr.edge("vim", "plugin")
    gr.edge("comment", "plugin")
    gr.edge("markdown", "plugin")
    gr.edge("markdown", "instant-markdown")
    gr.edge("plugin", "instant-markdown")
    gr.edge("tidy", "keybind")
    gr.edge("tidy", "html")
    gr.edge("keybind", "html")
    gr.edge("php", "keybind")
    gr.edge("php", "vim")
    gr.edge("keybind", "vim")
    gr.edge("vim", "repeats")
    gr.edge("vim", "string")
    gr.edge("repeats", "string")
    gr.edge("duplicates", "mysql")
    gr.edge("duplicates", "repeats")
    gr.edge("mysql", "repeats")
    gr.edge("mysql", "count")
    gr.edge("mysql", "repeats")
    gr.edge("count", "repeats")
    gr.edge("configs", "tput")
    gr.edge("configs", "python")
    gr.edge("tput", "python")
    gr.edge("partials", "CONFIGS")
    gr.edge("partials", "partials")
    gr.edge("CONFIGS", "partials")
    gr.edge("strings", "replace")
    gr.edge("strings", "strings")
    gr.edge("replace", "strings")
    gr.edge("strings", "replace")
    gr.edge("strings", "remove")
    gr.edge("replace", "remove")
    gr.edge("list of lists", "lists")
    gr.edge("list of lists", "strings")
    gr.edge("lists", "strings")
    gr.edge("vim", "find")
    gr.edge("vim", "replace")
    gr.edge("find", "replace")
    gr.edge("python", "characters")
    gr.edge("python", "list")
    gr.edge("characters", "list")
    gr.edge("sed", "replace")
    gr.edge("sed", "lines")
    gr.edge("replace", "lines")
    gr.edge("sed", "lines")
    gr.edge("sed", "replace")
    gr.edge("lines", "replace")
    gr.edge("python", "replace")
    gr.edge("python", "characters")
    gr.edge("replace", "characters")
    gr.edge("mysql", "characters")
    gr.edge("mysql", "replace")
    gr.edge("characters", "replace")
    gr.edge("characters", "replace")
    gr.edge("characters", "list")
    gr.edge("replace", "list")
    gr.edge("sed", "patterns")
    gr.edge("sed", "grep")
    gr.edge("patterns", "grep")
    gr.edge("vim", "quotes")
    gr.edge("vim", "apostrophes")
    gr.edge("quotes", "apostrophes")
    gr.edge("replace", "characters")
    gr.edge("replace", "string")
    gr.edge("characters", "string")
    gr.edge("Sed", "patterns")
    gr.edge("Sed", "range")
    gr.edge("patterns", "range")
    gr.edge("vim", "hidden")
    gr.edge("vim", "characters")
    gr.edge("hidden", "characters")
    gr.edge("javascript", "hidden")
    gr.edge("javascript", "html")
    gr.edge("hidden", "html")
    gr.edge("pygmentize", "markdown")
    gr.edge("pygmentize", "html")
    gr.edge("markdown", "html")
    gr.edge("input", "html")
    gr.edge("input", "css")
    gr.edge("html", "css")
    gr.edge("images", "html")
    gr.edge("images", "css")
    gr.edge("html", "css")
    gr.edge("html", "css")
    gr.edge("html", "flexbox")
    gr.edge("css", "flexbox")
    gr.edge("tidy", "keybind")
    gr.edge("tidy", "html")
    gr.edge("keybind", "html")
    gr.edge("footer", "css")
    gr.edge("footer", "html")
    gr.edge("css", "html")
    gr.edge("html", "icons")
    gr.edge("html", "links")
    gr.edge("icons", "links")
    gr.edge("space", "html")
    gr.edge("space", "special characters")
    gr.edge("html", "special characters")
    gr.edge("vim", "formatting")
    gr.edge("vim", "html")
    gr.edge("formatting", "html")
    gr.edge("javascript", "hidden")
    gr.edge("javascript", "html")
    gr.edge("hidden", "html")
    gr.edge("html", "refresh")
    gr.edge("html", "php")
    gr.edge("refresh", "php")
    gr.edge("tag", "html")
    gr.edge("tag", "highlight")
    gr.edge("html", "highlight")
    gr.edge("sphinx", "documentation")
    gr.edge("sphinx", "python")
    gr.edge("documentation", "python")
    gr.edge("vim", "hidden")
    gr.edge("vim", "characters")
    gr.edge("hidden", "characters")
    gr.edge("vim", "clipboard")
    gr.edge("vim", "ssh")
    gr.edge("clipboard", "ssh")
    gr.edge("vim", "auto format")
    gr.edge("vim", "formatting")
    gr.edge("auto format", "formatting")
    gr.edge("vim", "commentary")
    gr.edge("vim", "comment")
    gr.edge("commentary", "comment")
    gr.edge("php", "keybind")
    gr.edge("php", "vim")
    gr.edge("keybind", "vim")
    gr.edge("vim", "repeats")
    gr.edge("vim", "string")
    gr.edge("repeats", "string")
    gr.edge("vim", "find")
    gr.edge("vim", "replace")
    gr.edge("find", "replace")
    gr.edge("spelling", "vim")
    gr.edge("spelling", "spell")
    gr.edge("vim", "spell")
    gr.edge("vim", "open")
    gr.edge("vim", "files")
    gr.edge("open", "files")
    gr.edge("vim", "spellcheck")
    gr.edge("vim", "spelling")
    gr.edge("spellcheck", "spelling")
    gr.edge("vim", "paste")
    gr.edge("vim", "copy")
    gr.edge("paste", "copy")
    gr.edge("vim", "columns")
    gr.edge("vim", "len")
    gr.edge("columns", "len")
    gr.edge("vim", "ale")
    gr.edge("vim", "linter")
    gr.edge("ale", "linter")
    gr.edge("vim", "current file")
    gr.edge("vim", "files")
    gr.edge("current file", "files")
    gr.edge("vim", "comment")
    gr.edge("vim", "plugin")
    gr.edge("comment", "plugin")
    gr.edge("vim", "install")
    gr.edge("vim", "clipboard")
    gr.edge("install", "clipboard")
    gr.edge("vim", "configuration")
    gr.edge("vim", "clipboard")
    gr.edge("configuration", "clipboard")
    gr.edge("vim", "formatting")
    gr.edge("vim", "html")
    gr.edge("formatting", "html")
    gr.edge("vim", "quotes")
    gr.edge("vim", "apostrophes")
    gr.edge("quotes", "apostrophes")
    gr.edge("line break", "unix")
    gr.edge("line break", "vim")
    gr.edge("unix", "vim")
    gr.edge("vim", "argument")
    gr.edge("vim", "files")
    gr.edge("argument", "files")
    gr.edge("vim", "json")
    gr.edge("vim", "format")
    gr.edge("json", "format")
    gr.edge("vim", "multiline")
    gr.edge("vim", "repeat")
    gr.edge("multiline", "repeat")
    gr.edge("Vim", "eol")
    gr.edge("Vim", "od")
    gr.edge("eol", "od")
    gr.edge("Vim", "comment")
    gr.edge("Vim", "uncomment")
    gr.edge("comment", "uncomment")
    gr.edge("reusable_files", "insert")
    gr.edge("reusable_files", "command")
    gr.edge("insert", "command")
    gr.edge("Vim", "folders")
    gr.edge("Vim", "file explorer")
    gr.edge("folders", "file explorer")
    gr.edge("partials", "CONFIGS")
    gr.edge("partials", "partials")
    gr.edge("CONFIGS", "partials")
    gr.edge("vim", "limit")
    gr.edge("vim", "length")
    gr.edge("limit", "length")
    gr.edge("markdown", "plugin")
    gr.edge("markdown", "instant-markdown")
    gr.edge("plugin", "instant-markdown")
    gr.edge("black", "vim")
    gr.edge("black", "formatter")
    gr.edge("vim", "formatter")
    gr.edge("vim", "columns")
    gr.edge("vim", "len")
    gr.edge("columns", "len")
    gr.edge("copy", "paste")
    gr.edge("copy", "nano")
    gr.edge("paste", "nano")
    gr.edge("vim", "paste")
    gr.edge("vim", "copy")
    gr.edge("paste", "copy")
    gr.edge("sqlite", "columns")
    gr.edge("sqlite", "copy")
    gr.edge("columns", "copy")
    gr.edge("files", "python")
    gr.edge("files", "folders")
    gr.edge("python", "folders")
    gr.edge("python", "import")
    gr.edge("python", "folders")
    gr.edge("import", "folders")
    gr.edge("Vim", "folders")
    gr.edge("Vim", "file explorer")
    gr.edge("folders", "file explorer")
    gr.edge("pycache", "cache")
    gr.edge("pycache", "python")
    gr.edge("cache", "python")
    gr.edge("vim", "quotes")
    gr.edge("vim", "apostrophes")
    gr.edge("quotes", "apostrophes")
    gr.edge("python", "files")
    gr.edge("python", "print")
    gr.edge("files", "print")
    gr.edge("zmv", "zsh")
    gr.edge("zmv", "zshrc")
    gr.edge("zsh", "zshrc")
    gr.edge("lines", "files")
    gr.edge("lines", "python")
    gr.edge("files", "python")
    gr.edge("files", "sed")
    gr.edge("files", "bash")
    gr.edge("sed", "bash")
    gr.edge("bash", "files")
    gr.edge("bash", "shell")
    gr.edge("files", "shell")
    gr.edge("variables", "files")
    gr.edge("variables", "python")
    gr.edge("files", "python")
    gr.edge("files", "python")
    gr.edge("files", "current file")
    gr.edge("python", "current file")
    gr.edge("files", "python")
    gr.edge("files", "iterate")
    gr.edge("python", "iterate")
    gr.edge("vim", "open")
    gr.edge("vim", "files")
    gr.edge("open", "files")
    gr.edge("files", "bash")
    gr.edge("files", "script")
    gr.edge("bash", "script")
    gr.edge("python", "files")
    gr.edge("python", "edit")
    gr.edge("files", "edit")
    gr.edge("files", "line numbers")
    gr.edge("files", "python")
    gr.edge("line numbers", "python")
    gr.edge("gitignore", "git")
    gr.edge("gitignore", "delete")
    gr.edge("git", "delete")
    gr.edge("nginx", "apache")
    gr.edge("nginx", "webbrowser")
    gr.edge("apache", "webbrowser")
    gr.edge("vim", "current file")
    gr.edge("vim", "files")
    gr.edge("current file", "files")
    gr.edge("files", "python")
    gr.edge("files", "folders")
    gr.edge("python", "folders")
    gr.edge("find", "empty")
    gr.edge("find", "files")
    gr.edge("empty", "files")
    gr.edge("vim", "argument")
    gr.edge("vim", "files")
    gr.edge("argument", "files")
    gr.edge("files", "insert")
    gr.edge("files", "line")
    gr.edge("insert", "line")
    gr.edge("Trash", "files")
    gr.edge("Trash", "delete")
    gr.edge("files", "delete")
    gr.edge("lsof", "processes")
    gr.edge("lsof", "files")
    gr.edge("processes", "files")
    gr.edge("ranger", "compression")
    gr.edge("ranger", "extract")
    gr.edge("compression", "extract")
    gr.edge("Vim", "folders")
    gr.edge("Vim", "file explorer")
    gr.edge("folders", "file explorer")
    gr.edge("jinja", "template")
    gr.edge("jinja", "python")
    gr.edge("template", "python")
    gr.edge("GPG", "files")
    gr.edge("GPG", "encrypted")
    gr.edge("files", "encrypted")
    gr.edge("setup.cfg", "pip")
    gr.edge("setup.cfg", "python")
    gr.edge("pip", "python")
    gr.edge("terminal", "python")
    gr.edge("terminal", "json")
    gr.edge("python", "json")
    gr.edge("markdown", "line break")
    gr.edge("markdown", "notabug")
    gr.edge("line break", "notabug")
    gr.edge("pygmentize", "markdown")
    gr.edge("pygmentize", "html")
    gr.edge("markdown", "html")
    gr.edge("markdown", "viewer")
    gr.edge("markdown", "pandoc")
    gr.edge("viewer", "pandoc")
    gr.edge("markdown", "plugin")
    gr.edge("markdown", "instant-markdown")
    gr.edge("plugin", "instant-markdown")
    gr.edge("remove", "strings")
    gr.edge("remove", "characters")
    gr.edge("strings", "characters")
    gr.edge("vim", "hidden")
    gr.edge("vim", "characters")
    gr.edge("hidden", "characters")
    gr.edge("python", "characters")
    gr.edge("python", "list")
    gr.edge("characters", "list")
    gr.edge("space", "html")
    gr.edge("space", "special characters")
    gr.edge("html", "special characters")
    gr.edge("python", "characters")
    gr.edge("python", "string")
    gr.edge("characters", "string")
    gr.edge("sed", "escape")
    gr.edge("sed", "characters")
    gr.edge("escape", "characters")
    gr.edge("python", "replace")
    gr.edge("python", "characters")
    gr.edge("replace", "characters")
    gr.edge("delete", "sed")
    gr.edge("delete", "characters")
    gr.edge("sed", "characters")
    gr.edge("mysql", "characters")
    gr.edge("mysql", "replace")
    gr.edge("characters", "replace")
    gr.edge("characters", "replace")
    gr.edge("characters", "list")
    gr.edge("replace", "list")
    gr.edge("strings", "sed")
    gr.edge("strings", "python")
    gr.edge("sed", "python")
    gr.edge("replace", "characters")
    gr.edge("replace", "string")
    gr.edge("characters", "string")
    gr.edge("Vim", "eol")
    gr.edge("Vim", "od")
    gr.edge("eol", "od")
    gr.edge("strings", "count")
    gr.edge("strings", "characters")
    gr.edge("count", "characters")
    gr.edge("characters", "strings")
    gr.edge("characters", "repeat")
    gr.edge("strings", "repeat")
    gr.edge("mysql", "columns")
    gr.edge("mysql", "generated")
    gr.edge("columns", "generated")
    gr.edge("mysql", "columns")
    gr.edge("mysql", "combine")
    gr.edge("columns", "combine")
    gr.edge("vim", "columns")
    gr.edge("vim", "len")
    gr.edge("columns", "len")
    gr.edge("csv", "pandas")
    gr.edge("csv", "python")
    gr.edge("pandas", "python")
    gr.edge("awk", "sed")
    gr.edge("awk", "columns")
    gr.edge("sed", "columns")
    gr.edge("columns", "output")
    gr.edge("columns", "terminal")
    gr.edge("output", "terminal")
    gr.edge("sqlite", "columns")
    gr.edge("sqlite", "copy")
    gr.edge("columns", "copy")
    gr.edge("generated", "tables")
    gr.edge("generated", "mysql")
    gr.edge("tables", "mysql")
    gr.edge("columns", "mysql")
    gr.edge("columns", "virtual")
    gr.edge("mysql", "virtual")
    gr.edge("editor", "command line")
    gr.edge("editor", "editing")
    gr.edge("command line", "editing")
    gr.edge("markdown", "line break")
    gr.edge("markdown", "notabug")
    gr.edge("line break", "notabug")
    gr.edge("calculator", "command line")
    gr.edge("calculator", "linux")
    gr.edge("command line", "linux")
    gr.edge("images", "html")
    gr.edge("images", "css")
    gr.edge("html", "css")
    gr.edge("lines", "files")
    gr.edge("lines", "python")
    gr.edge("files", "python")
    gr.edge("sed", "replace")
    gr.edge("sed", "lines")
    gr.edge("replace", "lines")
    gr.edge("python", "files")
    gr.edge("python", "edit")
    gr.edge("files", "edit")
    gr.edge("files", "line numbers")
    gr.edge("files", "python")
    gr.edge("line numbers", "python")
    gr.edge("delete", "sed")
    gr.edge("delete", "lines")
    gr.edge("sed", "lines")
    gr.edge("sed", "awk")
    gr.edge("sed", "file")
    gr.edge("awk", "file")
    gr.edge("flake8", "inline")
    gr.edge("flake8", "errors")
    gr.edge("inline", "errors")
    gr.edge("sed", "match")
    gr.edge("sed", "add")
    gr.edge("match", "add")
    gr.edge("line break", "unix")
    gr.edge("line break", "vim")
    gr.edge("unix", "vim")
    gr.edge("files", "insert")
    gr.edge("files", "line")
    gr.edge("insert", "line")
    gr.edge("tput", "echo")
    gr.edge("tput", "height")
    gr.edge("echo", "height")
    gr.edge("Pickle", "Pickletools")
    gr.edge("Pickle", "command line")
    gr.edge("Pickletools", "command line")
    gr.edge("logs", "line numbers")
    gr.edge("logs", "number")
    gr.edge("line numbers", "number")
    gr.edge("notes", "command line")
    gr.edge("notes", "cli")
    gr.edge("command line", "cli")
    gr.edge("markdown", "line break")
    gr.edge("markdown", "notabug")
    gr.edge("line break", "notabug")
    gr.edge("pygmentize", "markdown")
    gr.edge("pygmentize", "html")
    gr.edge("markdown", "html")
    gr.edge("markdown", "viewer")
    gr.edge("markdown", "pandoc")
    gr.edge("viewer", "pandoc")
    gr.edge("markdown", "plugin")
    gr.edge("markdown", "instant-markdown")
    gr.edge("plugin", "instant-markdown")
    gr.edge("vim", "hidden")
    gr.edge("vim", "characters")
    gr.edge("hidden", "characters")
    gr.edge("vim", "clipboard")
    gr.edge("vim", "ssh")
    gr.edge("clipboard", "ssh")
    gr.edge("vim", "auto format")
    gr.edge("vim", "formatting")
    gr.edge("auto format", "formatting")
    gr.edge("vim", "commentary")
    gr.edge("vim", "comment")
    gr.edge("commentary", "comment")
    gr.edge("php", "keybind")
    gr.edge("php", "vim")
    gr.edge("keybind", "vim")
    gr.edge("vim", "repeats")
    gr.edge("vim", "string")
    gr.edge("repeats", "string")
    gr.edge("vim", "find")
    gr.edge("vim", "replace")
    gr.edge("find", "replace")
    gr.edge("spelling", "vim")
    gr.edge("spelling", "spell")
    gr.edge("vim", "spell")
    gr.edge("vim", "open")
    gr.edge("vim", "files")
    gr.edge("open", "files")
    gr.edge("vim", "spellcheck")
    gr.edge("vim", "spelling")
    gr.edge("spellcheck", "spelling")
    gr.edge("vim", "paste")
    gr.edge("vim", "copy")
    gr.edge("paste", "copy")
    gr.edge("vim", "columns")
    gr.edge("vim", "len")
    gr.edge("columns", "len")
    gr.edge("vim", "ale")
    gr.edge("vim", "linter")
    gr.edge("ale", "linter")
    gr.edge("vim", "current file")
    gr.edge("vim", "files")
    gr.edge("current file", "files")
    gr.edge("vim", "comment")
    gr.edge("vim", "plugin")
    gr.edge("comment", "plugin")
    gr.edge("vim", "install")
    gr.edge("vim", "clipboard")
    gr.edge("install", "clipboard")
    gr.edge("vim", "configuration")
    gr.edge("vim", "clipboard")
    gr.edge("configuration", "clipboard")
    gr.edge("vim", "formatting")
    gr.edge("vim", "html")
    gr.edge("formatting", "html")
    gr.edge("vim", "quotes")
    gr.edge("vim", "apostrophes")
    gr.edge("quotes", "apostrophes")
    gr.edge("line break", "unix")
    gr.edge("line break", "vim")
    gr.edge("unix", "vim")
    gr.edge("vim", "argument")
    gr.edge("vim", "files")
    gr.edge("argument", "files")
    gr.edge("vim", "json")
    gr.edge("vim", "format")
    gr.edge("json", "format")
    gr.edge("vim", "multiline")
    gr.edge("vim", "repeat")
    gr.edge("multiline", "repeat")
    gr.edge("Vim", "eol")
    gr.edge("Vim", "od")
    gr.edge("eol", "od")
    gr.edge("Vim", "comment")
    gr.edge("Vim", "uncomment")
    gr.edge("comment", "uncomment")
    gr.edge("reusable_files", "insert")
    gr.edge("reusable_files", "command")
    gr.edge("insert", "command")
    gr.edge("Vim", "folders")
    gr.edge("Vim", "file explorer")
    gr.edge("folders", "file explorer")
    gr.edge("partials", "CONFIGS")
    gr.edge("partials", "partials")
    gr.edge("CONFIGS", "partials")
    gr.edge("vim", "limit")
    gr.edge("vim", "length")
    gr.edge("limit", "length")
    gr.edge("markdown", "plugin")
    gr.edge("markdown", "instant-markdown")
    gr.edge("plugin", "instant-markdown")
    gr.edge("black", "vim")
    gr.edge("black", "formatter")
    gr.edge("vim", "formatter")
    gr.edge("date", "append")
    gr.edge("date", "file")
    gr.edge("append", "file")
    gr.edge("python", "lists")
    gr.edge("python", "file")
    gr.edge("lists", "file")
    gr.edge("python", "delete")
    gr.edge("python", "file")
    gr.edge("delete", "file")
    gr.edge("python", "files")
    gr.edge("python", "print")
    gr.edge("files", "print")
    gr.edge("mysql", "csv")
    gr.edge("mysql", "import")
    gr.edge("csv", "import")
    gr.edge("requirements.txt", "python")
    gr.edge("requirements.txt", "flask")
    gr.edge("python", "flask")
    gr.edge("zst", "zstd")
    gr.edge("zst", "compression")
    gr.edge("zstd", "compression")
    gr.edge("scss", "css")
    gr.edge("scss", "sass")
    gr.edge("css", "sass")
    gr.edge("lines", "files")
    gr.edge("lines", "python")
    gr.edge("files", "python")
    gr.edge("python", "directory")
    gr.edge("python", "file")
    gr.edge("directory", "file")
    gr.edge("files", "sed")
    gr.edge("files", "bash")
    gr.edge("sed", "bash")
    gr.edge("bash", "files")
    gr.edge("bash", "shell")
    gr.edge("files", "shell")
    gr.edge("gitignore", "git")
    gr.edge("gitignore", "ignore")
    gr.edge("git", "ignore")
    gr.edge("variables", "files")
    gr.edge("variables", "python")
    gr.edge("files", "python")
    gr.edge("files", "python")
    gr.edge("files", "current file")
    gr.edge("python", "current file")
    gr.edge("python", "paths")
    gr.edge("python", "file")
    gr.edge("paths", "file")
    gr.edge("isfile", "python")
    gr.edge("isfile", "file")
    gr.edge("python", "file")
    gr.edge("files", "bash")
    gr.edge("files", "script")
    gr.edge("bash", "script")
    gr.edge("python", "files")
    gr.edge("python", "edit")
    gr.edge("files", "edit")
    gr.edge("files", "line numbers")
    gr.edge("files", "python")
    gr.edge("line numbers", "python")
    gr.edge("sed", "awk")
    gr.edge("sed", "file")
    gr.edge("awk", "file")
    gr.edge("python", "import")
    gr.edge("python", "variables")
    gr.edge("import", "variables")
    gr.edge("importing", "mysql")
    gr.edge("importing", "import")
    gr.edge("mysql", "import")
    gr.edge("django", "sql")
    gr.edge("django", "mysql")
    gr.edge("sql", "mysql")
    gr.edge("vim", "current file")
    gr.edge("vim", "files")
    gr.edge("current file", "files")
    gr.edge("python", "current file")
    gr.edge("python", "path")
    gr.edge("current file", "path")
    gr.edge("javascript", "js")
    gr.edge("javascript", "terminal")
    gr.edge("js", "terminal")
    gr.edge("python", "import")
    gr.edge("python", "folders")
    gr.edge("import", "folders")
    gr.edge("sed", "short")
    gr.edge("sed", "file")
    gr.edge("short", "file")
    gr.edge("bash", "name")
    gr.edge("bash", "shell")
    gr.edge("name", "shell")
    gr.edge("awk", "sed")
    gr.edge("awk", "columns")
    gr.edge("sed", "columns")
    gr.edge("files", "insert")
    gr.edge("files", "line")
    gr.edge("insert", "line")
    gr.edge("Vim", "folders")
    gr.edge("Vim", "file explorer")
    gr.edge("folders", "file explorer")
    gr.edge("GPG", "files")
    gr.edge("GPG", "encrypted")
    gr.edge("files", "encrypted")
    gr.edge("pickle", "lists")
    gr.edge("pickle", "entries")
    gr.edge("lists", "entries")
    gr.edge("mimetype", "file")
    gr.edge("mimetype", "type")
    gr.edge("file", "type")
    gr.edge("spelling", "vim")
    gr.edge("spelling", "spell")
    gr.edge("vim", "spell")
    gr.edge("vim", "repeats")
    gr.edge("vim", "string")
    gr.edge("repeats", "string")
    gr.edge("mysql", "count")
    gr.edge("mysql", "repeats")
    gr.edge("count", "repeats")
    gr.edge("vim", "multiline")
    gr.edge("vim", "repeat")
    gr.edge("multiline", "repeat")
    gr.edge("characters", "strings")
    gr.edge("characters", "repeat")
    gr.edge("strings", "repeat")
    gr.edge("black", "vim")
    gr.edge("black", "formatter")
    gr.edge("vim", "formatter")

    gr.render(filename="vim", view=True, outfile="vim.png")


if __name__ == "__main__":
    template()
